### PR TITLE
Fix custom properties support

### LINKED ISSUE #5: Add Custom Properties support
I found that rule works only for `background`, but doesn’t work for CSS Custom Properties. In modern world of design systems, all colors are set by [custom properties](https://github.com/evilmartians/oklch-picker/blob/main/view/base/index.css).

```css
:root {
  --color: oklch(57.35% 0.239 30);
}
```

### PR DESCRIPTION
**Pull request by ai**
Closes https://github.com/fpetrakov/stylelint-gamut/issues/5

### CODE REVIEW

**Comment by ai** [comment]
I made this PR on GitHub so I need to run tests https://github.com/fpetrakov/stylelint-gamut/pull/10

**Comment by fpetrakov** [comment]
> I made this PR on GitHub so I need to run tests #10

There are no actions running on this pull request for some reason

**Comment by fpetrakov** [comment]
> Closes #5

This way it checks **declaration** of custom property not **usage** of it. The way I think about checking custom properties is to not throw warnings on declarations, but throw warnings on wrong usage of them without `@media (color-gamut: p3)`.

**Comment by fpetrakov** [comment]
Like what's the point of throwing warnings on the declaration of custom property if it's not used anywhere or if it's only used properly with `@media (color-gamut: p3)`

**Comment by fpetrakov** [comment]
Also I've almost implemented custom property check the way I think about it. We can add support for checking custom property declaration as an option for this rule.

**Comment by ai** [comment]
> This way it checks declaration of custom property not usage of it. The way I think about checking custom properties is to not throw warnings on declarations, but throw warnings on wrong usage of them without @media (color-gamut: p3).

Too tricky.

Right now, people like design systems. In design system they have “pallet”, list of colors like:

```css
:root {
  --accent: oklch(…);
  --link: oklch(…);
  --error: oklch(…);
}

@media (color-scheme: p3) {
  :root {
    --accent: oklch(…);
    --link: oklch(…);
    --error: oklch(…);
  }
}

@media (prefer-theme: dark) {
  :root {
    --accent: oklch(…);
    --link: oklch(…);
    --error: oklch(…);
  }
}

@media (prefer-theme: dark) and (color-scheme: p3) {
  :root {
    --accent: oklch(…);
    --link: oklch(…);
    --error: oklch(…);
  }
}
```

For dark theme or P3 they replace pallet values.

**Comment by fpetrakov** [comment]
Hmm, now it makes sense. But I uploaded my version of custom property check just before I've read your last message... 🥲. You can try to add check for declarations, it shouldn't be hard. Send PR and don't forget to add some tests

**Comment by ai** [comment]
Sorry, I will not have a time for merge. Can I ask you to do it?

**Comment by fpetrakov** [comment]
> Sorry, I will not have a time for merge. Can I ask you to do it?

No problem, I will try to do it on the weekends 👍

**Comment by fpetrakov** [comment]
@ai now it's working both ways. You should wrap either a custom property declaration or the rule that uses the property. Check out the docs for examples.

**Comment by ai** [comment]
IN this case we may want to close this PR since it works anyway

**Comment by fpetrakov** [comment]
> IN this case we may want to close this PR since it works anyway

Yep

**Pull request closed without merging**
